repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform/
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs 
      - id: terraform_tflint 